import { defineConfig } from "tsdown";

export default defineConfig({
  clean: true,
  deps: { alwaysBundle: [/^@sphynx\//] },
  dts: { eager: true },
  entry: {
    api: "src/mock-api/index.ts",
    "api-runtime": "src/mock-api/runtime.ts",
    "api-context": "src/mock-api/context.ts",
    bin: "src/cli/main.ts",
    cli: "src/mock-cli/index.ts",
    command: "src/evals/command.ts",
    "cli-runtime": "src/mock-cli/runtime.ts",
    eval: "src/evals/index.ts",
    index: "src/index.ts",
    mcp: "src/mcp/index.ts",
    named: "src/evals/named.ts",
    "mcp-runtime": "src/mcp/runtime.ts",
    runner: "src/runner/index.ts",
    "runner-eve": "src/runner/eve/index.ts",
    "runner-eve-bin": "src/runner/eve/bin.ts",
    source: "src/evals/source.ts",
    validators: "src/validators.ts",
    "validator-runtime": "src/evals/validator-runtime.ts",
  },
  format: ["esm", "cjs"],
  target: "node20",
  tsconfig: "./tsconfig.build.json",
  treeshake: true,
});
