export const PROSE_CLASSES = [
  "text-[12px] text-muted-foreground leading-snug",
  "[&_a]:text-primary [&_a]:underline-offset-2 hover:[&_a]:underline",
  "[&_p]:mb-1.5",
  "[&_h1]:mb-1 [&_h1]:font-medium [&_h1]:text-[13px] [&_h1]:text-foreground",
  "[&_h2]:mb-1 [&_h2]:font-medium [&_h2]:text-[13px] [&_h2]:text-foreground",
  "[&_h3]:mb-1 [&_h3]:font-medium [&_h3]:text-[12px] [&_h3]:text-foreground",
  "[&_ul]:mb-1.5 [&_ul]:list-disc [&_ul]:pl-4",
  "[&_ol]:mb-1.5 [&_ol]:list-decimal [&_ol]:pl-4",
  "[&_li]:mb-0.5",
  "[&_code]:rounded-sm [&_code]:bg-muted/50 [&_code]:px-1 [&_code]:font-mono [&_code]:text-[11px]",
  "[&_pre]:no-scrollbar [&_pre]:mb-1.5 [&_pre]:overflow-x-auto [&_pre]:rounded-md [&_pre]:border [&_pre]:border-border [&_pre]:bg-muted/30 [&_pre]:p-2",
  "[&_blockquote]:mb-1.5 [&_blockquote]:border-border [&_blockquote]:border-l-2 [&_blockquote]:pl-2.5",
  "[&_summary]:cursor-pointer [&_summary]:select-none [&_summary]:text-foreground/80 [&_summary>*]:inline",
  "[&_details]:mb-1.5",
  "[&_img]:max-w-full",
  "[&_hr]:my-2 [&_hr]:border-border",
  "[&_table]:no-scrollbar [&_table]:mb-1.5 [&_table]:block [&_table]:w-max [&_table]:max-w-full [&_table]:border-collapse [&_table]:overflow-x-auto",
  "[&_td]:border [&_td]:border-border [&_td]:px-2 [&_td]:py-1 [&_td]:align-top [&_td]:[overflow-wrap:anywhere]",
  "[&_th]:border [&_th]:border-border [&_th]:bg-muted/30 [&_th]:px-2 [&_th]:py-1 [&_th]:text-left [&_th]:align-top [&_th]:font-medium [&_th]:text-foreground",
].join(" ");
